# Generated by Django 6.0.5 on 2026-05-15 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image_profile',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
