# Generated by Django 6.0.5 on 2026-05-15 07:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_profile_image_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('title', models.CharField(max_length=240)),
                ('decription', models.TextField(blank=True, null=True)),
                ('website_link', models.CharField(blank=True, max_length=2000, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('proccessing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], max_length=240)),
                ('cleaned_zip', models.FileField(blank=True, null=True, upload_to='zips/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='users.profile')),
            ],
        ),
    ]
