# Generated by Django 6.0.5 on 2026-05-18 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_projects_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='profile',
            new_name='owner',
        ),
    ]
